### ISSUE TITLE
Plugin `volkovlabs-env-datasource` not provisioning filter from datasource.yml on grafana 10.2.2

### ISSUE THREAD

**Issue by Nine-H** [VolkovLabs/volkovlabs.io#634]
No matter what I try I can't seem to get the filter to populate correctly, even with verbatim config from documentation.

**Comment by mikhail-vl** [comment]
@Nine-H Have you looked at the documentation: https://volkovlabs.io/plugins/volkovlabs-env-datasource/provisioning/ ?

```
datasources:
  - name: Environment
    type: volkovlabs-env-datasource
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    editable: true
    jsonData:
      filter: GF_
```
